#### Assignment_2


## Section A: Data Structures & Control Structures

## 1.      Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [1]:
nums = [10, 20, 30, 40, 50]
print("Original:", nums)

nums.append(60)          # add one element at end
print("After append:", nums)

nums.extend([70, 80])    # add multiple elements
print("After extend:", nums)

nums.insert(1, 15)       # insert at index 1
print("After insert:", nums)

nums.remove(30)          # remove first occurrence of value 30
print("After remove:", nums)

popped = nums.pop()      # remove last element
print("Popped value:", popped)
print("After pop:", nums)

# index of a value
print("Index of 40:", nums.index(40))   

# count of a value
print("Count of 20:", nums.count(20))   

nums.sort()              # sort ascending
print("After sort:", nums)

nums.reverse()           # reverse in-place
print("After reverse:", nums)

nums.clear()             # remove all elements
print("After clear:", nums)

Original: [10, 20, 30, 40, 50]
After append: [10, 20, 30, 40, 50, 60]
After extend: [10, 20, 30, 40, 50, 60, 70, 80]
After insert: [10, 15, 20, 30, 40, 50, 60, 70, 80]
After remove: [10, 15, 20, 40, 50, 60, 70, 80]
Popped value: 80
After pop: [10, 15, 20, 40, 50, 60, 70]
Index of 40: 3
Count of 20: 1
After sort: [10, 15, 20, 40, 50, 60, 70]
After reverse: [70, 60, 50, 40, 20, 15, 10]
After clear: []


### 2.      Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.


In [20]:
students = ("Vajay", "Allu Arjun ", "Ram")
print(students)


('Vajay', 'Allu Arjun ', 'Ram')


In [21]:
students[1] = "Bobby"      #Trying to assign students[1] = "Bobby" causes a TypeError because tuples are immutable, meaning their elements cannot be changed after creation.

TypeError: 'tuple' object does not support item assignment

### 3. Create a set of integers with some duplicate values. Print the set and explain the output.

In [22]:
nums_with_duplicates = {1, 2, 2, 3, 3, 3, 4}
print(nums_with_duplicates)

#The printed set will contain each number only once because a set automatically removes duplicates and keeps only unique elements.

{1, 2, 3, 4}


### 4.      Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [23]:
person = {
    "name": "Rahul",
    "age": 20,
    "city": "Mumbai"
}

person["age"] = 21                 # update age
person["email"] = "rahul@gmail.com" # add new key
print(person)                      

{'name': 'Rahul', 'age': 21, 'city': 'Mumbai', 'email': 'rahul@gmail.com'}


### 5.       Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [24]:
age = 19

if age >= 18:
    print("Eligible to vote")
else:
    print("Not eligible to vote") 

Eligible to vote


### 6. Given a 'marks' variable, print the grade:

In [27]:
marks = 82  

if marks >= 90:
    print("A")
elif marks >= 75:
    print("B")
elif marks >= 50:
    print("C")
else:
    print("Fail") 

B


### 7.      Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.


In [28]:
num = -5 

if num > 0:
    if num % 2 == 0:
        print("Number is positive and even")
    else:
        print("Number is positive but odd")
elif num == 0:
    print("Number is zero")
else:
    print("Number is negative") 

Number is negative


## Section B: Numpy

### 1. Create:- A scalar using np.array(5)

In [29]:
import numpy as np

# Scalar
scalar = np.array(5)
print("Scalar:", scalar)

# 1D array with values 1 to 5
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D array:", arr_1d)

# 2D array (2x3) with values 10 to 60 step 10
arr_2d = np.array([[10, 20, 30],
                   [40, 50, 60]])
print("2D array:\n", arr_2d)  


Scalar: 5
1D array: [1 2 3 4 5]
2D array:
 [[10 20 30]
 [40 50 60]]


### 2.  Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().


In [30]:
import numpy as np

# 4x4 array of random integers from 0 to 100 (inclusive of 0, exclusive of 101)
rand_arr = np.random.randint(0, 101, size=(4, 4))
print("Random 4x4 array:\n", rand_arr) 


Random 4x4 array:
 [[81 42 53 68]
 [49 39 21 49]
 [36 46 59 97]
 [71 38  2  0]]


### 3.  Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.


In [32]:
import numpy as np
import pandas as pd

# 3x3 numpy array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Convert to DataFrame with column names A, B, C
df = pd.DataFrame(arr, columns=['A', 'B', 'C'])
print(df) 


   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


### Section C: Exploring Pandas

In [33]:
import pandas as pd
import numpy as np

data = {
    "Name":  ["Amit", "Neha", "Ravi", "Sara", "Amit", "Vijay", "Priya", "Ravi", "Kiran", "Neha"],
    "Age":   [25, 30, 22, 28, 25, 35, 27, 22, 29, 30],
    "City":  ["Delhi", "Mumbai", "Chennai", "Delhi", "Delhi", "Pune", "Kolkata", "Chennai", "Mumbai", "Mumbai"],
    "Salary": [50000, 60000, np.nan, 65000, 50000, 70000, 62000, np.nan, 58000, 60000]
}

df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

print("\n.info():")
print(df.info())

print("\n.describe():")
print(df.describe())  


Original DataFrame:
    Name  Age     City   Salary
0   Amit   25    Delhi  50000.0
1   Neha   30   Mumbai  60000.0
2   Ravi   22  Chennai      NaN
3   Sara   28    Delhi  65000.0
4   Amit   25    Delhi  50000.0
5  Vijay   35     Pune  70000.0
6  Priya   27  Kolkata  62000.0
7   Ravi   22  Chennai      NaN
8  Kiran   29   Mumbai  58000.0
9   Neha   30   Mumbai  60000.0

.info():
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes
None

.describe():
             Age        Salary
count  10.000000      8.000000
mean   27.300000  59375.000000
std     4.001389   6864.765109
min    22.000000  50000.000000
25%    25.000000  56000.000000
50%    27.500000  60000

In [34]:
# Select 'Name' and 'City' columns
name_city = df[["Name", "City"]]
print("\nOnly Name and City columns:")
print(name_city) 

# Drop 'City' column (create a new DataFrame without City)
df_no_city = df.drop(columns=["City"])
print("\nDataFrame after dropping City column:")
print(df_no_city)  



Only Name and City columns:
    Name     City
0   Amit    Delhi
1   Neha   Mumbai
2   Ravi  Chennai
3   Sara    Delhi
4   Amit    Delhi
5  Vijay     Pune
6  Priya  Kolkata
7   Ravi  Chennai
8  Kiran   Mumbai
9   Neha   Mumbai

DataFrame after dropping City column:
    Name  Age   Salary
0   Amit   25  50000.0
1   Neha   30  60000.0
2   Ravi   22      NaN
3   Sara   28  65000.0
4   Amit   25  50000.0
5  Vijay   35  70000.0
6  Priya   27  62000.0
7   Ravi   22      NaN
8  Kiran   29  58000.0
9   Neha   30  60000.0


In [35]:
# Fill NaN in Salary with mean of Salary
salary_mean = df["Salary"].mean()
df["Salary"] = df["Salary"].fillna(salary_mean)

print("\nDataFrame after filling missing Salary with mean:")
print(df) 



DataFrame after filling missing Salary with mean:
    Name  Age     City   Salary
0   Amit   25    Delhi  50000.0
1   Neha   30   Mumbai  60000.0
2   Ravi   22  Chennai  59375.0
3   Sara   28    Delhi  65000.0
4   Amit   25    Delhi  50000.0
5  Vijay   35     Pune  70000.0
6  Priya   27  Kolkata  62000.0
7   Ravi   22  Chennai  59375.0
8  Kiran   29   Mumbai  58000.0
9   Neha   30   Mumbai  60000.0


In [36]:
# Remove duplicate rows (keep first occurrence)
df_no_duplicates = df.drop_duplicates()

print("\nDataFrame after removing duplicate rows:")
print(df_no_duplicates) 



DataFrame after removing duplicate rows:
    Name  Age     City   Salary
0   Amit   25    Delhi  50000.0
1   Neha   30   Mumbai  60000.0
2   Ravi   22  Chennai  59375.0
3   Sara   28    Delhi  65000.0
5  Vijay   35     Pune  70000.0
6  Priya   27  Kolkata  62000.0
8  Kiran   29   Mumbai  58000.0
